# Generated by Django 2.2.4 on 2023-01-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('number', models.CharField(default='', max_length=255)),
                ('treatment_field', models.TextField(default=None)),
                ('years_of_experience', models.CharField(default='', max_length=255)),
                ('desc', models.TextField(default=None)),
                ('certificate', models.FileField(default='', max_length=250, null=True, upload_to='certificates/')),
                ('photograph', models.FileField(default='', max_length=250, null=True, upload_to='photographs/')),
                ('password', models.CharField(max_length=255)),
                ('user_level', models.CharField(default='proccser', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
