# Generated by Django 2.2.4 on 2023-01-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('identity_number', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('telphone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('service_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='appMain.User')),
            ],
        ),
    ]
