# Generated by Django 2.2.4 on 2023-01-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
    ]
