# Generated by Django 2.2.4 on 2023-01-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0003_remove_order_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
