# Generated by Django 2.2.4 on 2023-01-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0006_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
    ]
