# Generated by Django 2.2.4 on 2023-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0007_auto_20230119_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_context',
            field=models.TextField(),
        ),
    ]
