# Generated by Django 2.2.4 on 2023-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0008_auto_20230119_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate',
            field=models.FileField(blank=True, default='', max_length=250, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.FileField(blank=True, default='', max_length=250, null=True, upload_to='photographs/'),
        ),
    ]
