# Generated by Django 2.2.4 on 2023-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0009_auto_20230219_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.FileField(blank=True, default='', max_length=250, null=True, upload_to='doctors_image/'),
        ),
    ]
