# Generated by Django 2.2.4 on 2023-04-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0011_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.FileField(blank=True, default='', max_length=250, null=True, upload_to='products_image/'),
        ),
    ]
