# Generated by Django 2.2.4 on 2023-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0013_auto_20230508_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, default='', max_length=250, null=True, upload_to='products_image/'),
        ),
    ]
