from django.urls import path
from . import views


urlpatterns = [
    path('',views.form_page),
    path('register',views.register),
    path('login',views.login),
    path('send_user_request/<int:id>',views.send_user_request),
    path('send_visitor_request',views.send_visitor_request),
    path('welcome_page',views.welcome_page),
    path('doctors_page',views.doctors_page),
    path('products_page',views.products_page),
    path('add_product_page',views.add_product_page),
    path('add_product_method',views.add_product_method),
    path('view_product/<int:id>',views.view_product),
    path('edit_product/<int:id>',views.edit_product),
    path('edit_product_method/<int:id>',views.edit_product_method),
    path('delete_product/<int:id>',views.delete_product),
    path('products_page_admin',views.products_page_admin),
    path('add_member_page',views.add_member_page),
    path('add_member',views.add_member_by_admin),
    path('register_page',views.register_page),
    path('login_page',views.login_page),
    path('dashboard_page',views.dashboard_page),
    path('edit_profile_by_admin/<int:id>',views.edit_by_admin_page),
    path('edit_method_by_admin/<int:id>',views. edit_method_by_admin),
    path('edit_method_by_therapist/<int:id>',views. edit_method_by_therapist),
    path('edit_login_page/<int:id>',views.edit_login_page),
    path('edit_login_info/<int:id>',views.edit_login_info),
    path('logout',views.logout),
    path('members_page',views.members_page),
    path('edit_member_page/<int:id>',views.edit_member_page),
    path('delete_member/<int:id>',views.del_member),
    path('dashboard_therpist',views.dash_therpist),
    path('add_request_page',views.add_request_page),
    path('add_request',views.add_request),
    path('requests_page',views.requests_page),
    path('view_request/<int:id>',views.view_request),
    path('view_therapist/<int:id>',views.view_therapist),
    path('delete_request/<int:id>',views.del_request),
    path('send_message_page',views.send_message_page),
    path('messages_page/<id>',views.messages_page),
    path('send_message_method',views.send_message_method),
    path('view_message_data/<int:id>',views.view_message_data),
    path('delete_message/<int:id>',views.delete_message),
    path('therapist_dashboard/<int:id>',views.therpist_dash),
    path('therapist_request/<int:id>',views.therpist_requests),
    path('del_therapist_request/<int:id>',views.del_therapist_request),
    path('therapist_profile/<int:id>',views.therapist_profile),
    path('therapist_login_data/<int:id>',views.therapist_login_data),
    path('therapist_messages/<int:id>',views.therapist_messages),
    path('therapist_send_message/<int:id>',views.therapist_send_message),
    path('therapist_message_data/<int:id>',views.therapist_message_data),
    path('delete_message_therapist/<int:id>',views.delete_message_therapist),
    path('therapist_request_data/<int:id>',views.therapist_request_data),
    path('card_page/<int:id>',views.card_page),
]
